// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"10","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"SRD_SuperToolsEngine","status":true,"description":"The heart of all maker-style plugins; it adds a playtesting editor that can be opened with F12.","parameters":{"Connect Editor":"true","Auto Open Window":"false","Auto Move Window":"true","Menu Editor Exempt List":"[\"Window_BattleLog\",\"Window_MapName\"]"}},
{"name":"SRD_HUDMaker","status":true,"description":"Allows developers to create their own map-based HUD through an in-game GUI window!","parameters":{"Active Updating":"false","Show During Events":"transparent","Map Global Condition":"","Battle Global Condition":"","Disable Delete Key":"true"}},
{"name":"fun with orfices","status":true,"description":"","parameters":{}},
{"name":"what to load function","status":true,"description":"","parameters":{}},
{"name":"where to save function","status":true,"description":"","parameters":{}},
{"name":"speech","status":true,"description":"","parameters":{}},
{"name":"b2 mon rando","status":true,"description":"","parameters":{}},
{"name":"b1 mon rando","status":true,"description":"","parameters":{}},
{"name":"b3 mon rando","status":true,"description":"","parameters":{}},
{"name":"b4 mon rando","status":true,"description":"","parameters":{}},
{"name":"lootfinder","status":true,"description":"","parameters":{}},
{"name":"b1 mon rando_test","status":true,"description":"","parameters":{}},
{"name":"room decriptions","status":true,"description":"","parameters":{}},
{"name":"which monster","status":true,"description":"","parameters":{}}
];
